version: "2.4"


networks:
  software-arquitectura:
    name: network-proyects
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1
  software:
    name: network-config-server
    external: true
services:
  ms-discovery:
    image: ms-discovery:0.0.1
    mem_limit: 200m
    ports:
      - "8761:8761"
    networks:
      - software-arquitectura
      - software
    volumes:
      - "/opt/local:/opt/arquitectura/logs"
  ms-gateway:
    image: ms-gateway:0.0.1
    mem_limit: 200m
    ports:
      - "8282:8282"
    networks:
      - software-arquitectura
      - software
    environment:
      - "EUREKA_URI=http://ms-discovery:8761/eureka"
      - "URI_CONFIG=http://config-server:8888"
    depends_on:
      ms-discovery:
        condition: service_started
    volumes:
      - "/opt/local:/opt/arquitectura/logs"
  credito:
    image: credito:0.0.1
    mem_limit: 200m
    ports:
      - "9010:9010"
    networks:
      - software-arquitectura
      - software
    environment:
      - "EUREKA_URI=http://ms-discovery:8761/eureka"
      - "URI_CONFIG=http://config-server:8888"
      - "URL_BD=jdbc:postgresql://localhost:5432/atm"
    volumes:
      - "/opt/local:/opt/arquitectura/logs"
    depends_on:
      ms-discovery:
        condition: service_started
#  ms-cuenta-atm:
#    image: ms-cuenta-atm:0.0.1
#    mem_limit: 200m
#    ports:
#      - "9020:9020"
#    networks:
#      - software-arquitectura
#      - software
#    environment:
#      - "EUREKA_URI=http://ms-discovery:8761/eureka"
#      - "URI_CONFIG=http://config-server:8888"
#    volumes:
#      - "/opt/local:/opt/arquitectura/logs"
#    depends_on:
#      ms-discovery:
#        condition: service_started
#  cliente:
#    image: cliente:0.0.1
#    mem_limit: 200m
#    ports:
#      - "9030:9030"
#    networks:
#      - software-arquitectura
#      - software
#    environment:
#      - "EUREKA_URI=http://ms-discovery:8761/eureka"
#      - "URI_CONFIG=http://config-server:8888"
#    volumes:
#      - "/opt/local:/opt/arquitectura/logs"
#    depends_on:
#      ms-discovery:
#        condition: service_started