spring:
  datasource:
    url: ${URL_BD:jdbc:postgresql://localhost:5432/atm}
    username: postgres
    password: postgres
  application:
    name: credito
server:
  port: ${SERVER_PORT:8090}
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}